### ISSUE TITLE
Directly not playing nice with HS-17 headless server

### ISSUE THREAD

**Issue by Bahnburner** [sentry07/DirectPy#8]
When attempting to add a new object using ```dtv = DIRECTV('10.0.0.151')``` the following error results:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/hass/lib/python3.6/site-packages/DirectPy.py", line 33, in __init__
    self.get_tuned()
  File "/srv/hass/lib/python3.6/site-packages/DirectPy.py", line 74, in get_tuned
    self.channel = self._combine_channel(jResp['major'],jResp['minor'])
KeyError: 'major'
```

This might be caused by the HS-17 having no video output capabilities.

**Comment by sentry07** [comment]
I don't have Directv service anymore so my ability to maintain and test this code is hindered. But what it looks like you need to do is control the clients from the HS-17 by using their MAC address in the clientaddr parameter when creating a new instance. 

For example:
dtv = DIRECTV('10.0.0.151',clientaddr='000A959D6816')

Since the HS-17 is not a controllable box, this is not really a code issue with this library.

**Comment by Bahnburner** [comment]
Thanks for the response. I'll try your recommendation.
